### PR TITLE
Added a few scripts

### PR DESCRIPTION
**Pull request by BodenM**
Youtube search and DevOps reactions gif poster.

### CODE REVIEW

**Comment by TRManderson** [comment]
I'm gonna veto these, we don't actually need them. Unless you have a good case besides "they're fun"?

**Comment by BodenM** [comment]
Youtube search is handy, easier than going to YouTube to search for a video to paste into the chat. DevOps one is mostly just for fun though.

**Comment by joeladdison** [comment]
A YouTube title retriever can be useful, but searching can be done much more effectively on the actual site.

**Comment by TRManderson** [comment]
Eh, why not then I guess?

**Pull request merged**
