### PR TITLE
Added gImages search

### PR DESCRIPTION
**Pull request by BodenM**

### CODE REVIEW

**Comment by TRManderson** [comment]
Didn't need to do half this m8

**Comment by TRManderson** [comment]
You just needed to add it to external-scripts.json

**Comment by BodenM** [comment]
really

**Comment by BodenM** [comment]
(ノಠ益ಠ)ノ彡┻━┻

**Comment by TRManderson** [comment]
:heart: Yep, that's it

**Comment by TRManderson** [comment]
Normally you have to add it to package.json too, but it might still be there

**Pull request closed without merging**
