### PR TITLE
Changed npm install to npm update and bug fixes

### PR DESCRIPTION
**Pull request by lewisjb**

### CODE REVIEW

**Comment by lewisjb** [comment]
Sorry about the extra commit, forgot to fetch upstream :@

**Comment by TRManderson** [comment]
Can you add the trailing newlines back pls?

**Comment by lewisjb** [comment]
Ahh yea sure sorry

**Comment by TRManderson** [comment]
Technically this has been merged, but I did it manually on my end via cherry-pick so GH doesn't see it that way.

**Pull request closed without merging**
