### PR TITLE
Hopefully fix race condition

### PR DESCRIPTION
**Pull request by somebody1234**

### CODE REVIEW

**Comment by lewisjb** [comment]
"Hopefully", I'm assuming that means you didn't test it?

**Comment by TRManderson** [comment]
What's the race condition?

**Comment by lewisjb** [comment]
@TRManderson based off the code changes, I'd say the race condition of sending "Here are my commands", and the actual list of commands. I think concatenating them into 1 message would be a better solution, but that's not a big deal

**Comment by TRManderson** [comment]
Yep just tested it to confirm

**Comment by somebody1234** [comment]
Yeah sorry seems like the slack adapter for hubot doesn't support sending multiple messages

**Comment by TRManderson** [comment]
Gonna change up the deployment via Jenkins then I'll merge this PR to test it

**Pull request merged**
